<?php
/**
 * Default professional font catalog (Google Fonts + system fallbacks).
 *
 * @package PCKZCanonicalEngine
 * @return array<string,array>
 */

defined( 'ABSPATH' ) || exit;

return array(
	'russo-one'        => array(
		'label'     => 'Russo One — Technisch kräftig',
		'category'  => 'technical',
		'family'    => 'Russo One',
		'source'    => 'google',
		'google_id' => 'Russo+One',
		'sample'    => 'LASER 01',
	),
	'cinzel'           => array(
		'label'     => 'Cinzel — Luxus klassisch',
		'category'  => 'luxury',
		'family'    => 'Cinzel',
		'source'    => 'google',
		'google_id' => 'Cinzel:wght@400;700',
		'sample'    => 'PREMIUM',
	),
	'playfair'         => array(
		'label'     => 'Playfair Display — Elegant',
		'category'  => 'elegant',
		'family'    => 'Playfair Display',
		'source'    => 'google',
		'google_id' => 'Playfair+Display:wght@700',
		'sample'    => 'Style',
	),
	'bodoni'           => array(
		'label'     => 'Bodoni Moda — Premium Serif',
		'category'  => 'premium',
		'family'    => 'Bodoni Moda',
		'source'    => 'google',
		'google_id' => 'Bodoni+Moda:wght@700',
		'sample'    => 'ELITE',
	),
	'poppins'          => array(
		'label'     => 'Poppins — Modern clean',
		'category'  => 'modern',
		'family'    => 'Poppins',
		'source'    => 'google',
		'google_id' => 'Poppins:wght@600;700',
		'sample'    => 'Modern',
	),
	'inter'            => array(
		'label'     => 'Inter — Modern neutral',
		'category'  => 'modern',
		'family'    => 'Inter',
		'source'    => 'google',
		'google_id' => 'Inter:wght@600;700',
		'sample'    => 'Frame',
	),
	'merriweather'     => array(
		'label'     => 'Merriweather — Klassisch',
		'category'  => 'classic',
		'family'    => 'Merriweather',
		'source'    => 'google',
		'google_id' => 'Merriweather:wght@700',
		'sample'    => 'Classic',
	),
	'lora'             => array(
		'label'     => 'Lora — Elegant Serif',
		'category'  => 'elegant',
		'family'    => 'Lora',
		'source'    => 'google',
		'google_id' => 'Lora:wght@600;700',
		'sample'    => 'Fine',
	),
	'racing-sans'      => array(
		'label'     => 'Racing Sans One — Sport',
		'category'  => 'sport',
		'family'    => 'Racing Sans One',
		'source'    => 'google',
		'google_id' => 'Racing+Sans+One',
		'sample'    => 'SPEED',
	),
	'staatliches'      => array(
		'label'     => 'Staatliches — Sport Display',
		'category'  => 'sport',
		'family'    => 'Staatliches',
		'source'    => 'google',
		'google_id' => 'Staatliches',
		'sample'    => 'RACE',
	),
	'share-tech-mono'  => array(
		'label'     => 'Share Tech Mono — Technik',
		'category'  => 'technical',
		'family'    => 'Share Tech Mono',
		'source'    => 'google',
		'google_id' => 'Share+Tech+Mono',
		'sample'    => 'CODE-01',
	),
	'jetbrains-mono'   => array(
		'label'     => 'JetBrains Mono — Technisch',
		'category'  => 'technical',
		'family'    => 'JetBrains Mono',
		'source'    => 'google',
		'google_id' => 'JetBrains+Mono:wght@700',
		'sample'    => 'SYS.A1',
	),
	'bebas-neue'       => array(
		'label'     => 'Bebas Neue — Display hoch',
		'category'  => 'display',
		'family'    => 'Bebas Neue',
		'source'    => 'google',
		'google_id' => 'Bebas+Neue',
		'sample'    => 'FRAME',
	),
	'anton'            => array(
		'label'     => 'Anton — Display breit',
		'category'  => 'display',
		'family'    => 'Anton',
		'source'    => 'google',
		'google_id' => 'Anton',
		'sample'    => 'POWER',
	),
	'black-ops'        => array(
		'label'     => 'Black Ops One — Military',
		'category'  => 'sport',
		'family'    => 'Black Ops One',
		'source'    => 'google',
		'google_id' => 'Black+Ops+One',
		'sample'    => 'OPS-7',
	),
	'orbitron'         => array(
		'label'     => 'Orbitron — Futuristisch',
		'category'  => 'technical',
		'family'    => 'Orbitron',
		'source'    => 'google',
		'google_id' => 'Orbitron:wght@700',
		'sample'    => '2077',
	),
	'oswald'           => array(
		'label'     => 'Oswald — Sport schmal',
		'category'  => 'sport',
		'family'    => 'Oswald',
		'source'    => 'google',
		'google_id' => 'Oswald:wght@600;700',
		'sample'    => 'SLIM',
	),
	'montserrat'       => array(
		'label'     => 'Montserrat — Modern geometrisch',
		'category'  => 'modern',
		'family'    => 'Montserrat',
		'source'    => 'google',
		'google_id' => 'Montserrat:wght@600;700',
		'sample'    => 'GEO',
	),
	'archivo-black'    => array(
		'label'     => 'Archivo Black — Extra bold',
		'category'  => 'display',
		'family'    => 'Archivo Black',
		'source'    => 'google',
		'google_id' => 'Archivo+Black',
		'sample'    => 'BOLD',
	),
	'great-vibes'      => array(
		'label'     => 'Great Vibes — Script Luxus',
		'category'  => 'luxury',
		'family'    => 'Great Vibes',
		'source'    => 'google',
		'google_id' => 'Great+Vibes',
		'sample'    => 'Signature',
	),
	'roboto'           => array(
		'label'     => 'Roboto — Neutral Sans',
		'category'  => 'modern',
		'family'    => 'Roboto',
		'source'    => 'google',
		'google_id' => 'Roboto:wght@700',
		'sample'    => 'Text',
	),
	'ubuntu'           => array(
		'label'     => 'Ubuntu — Rund modern',
		'category'  => 'modern',
		'family'    => 'Ubuntu',
		'source'    => 'google',
		'google_id' => 'Ubuntu:wght@700',
		'sample'    => 'Round',
	),
);
